'use client'

import React, { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'es' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Nav
    'nav.profile': 'Perfil',
    'nav.architecture': 'Arquitectura',
    'nav.experience': 'Experiencia',
    'nav.siem': 'SIEM',
    'nav.audit': 'Auditoría',
    'nav.blog': 'Inteligencia',
    'nav.stack': 'Stack',
    'nav.projects': 'Casos de Éxito',
    'nav.contact': 'Contacto',

    // Hero
    'hero.title.first': 'Juan Felipe',
    'hero.title.last': 'Palacios',
    'hero.subtitle': 'Project Manager IT | Cybersecurity Leader | SysAdmin',
    'hero.role': 'IT/OT Cybersecurity Architect',
    'hero.tagline': 'Resiliencia digital para infraestructuras críticas y el sector de Oil & Gas.',
    'hero.cta.history': 'Historial Crítico',
    'hero.cta.architecture': 'Arquitectura OT',
    'hero.system_active': 'Sistema Activo',
    'hero.protocol': 'Protocolo IT/OT · Ciberseguridad',
    'hero.role_details': 'Project Manager IT | Cybersecurity Leader | SysAdmin',
    'hero.scroll': 'Sistema de Scroll',

    // Perfil
    'profile.label': 'Sobre mí',
    'profile.title': 'Perfil',
    'profile.highlight': 'Profesional',
    'profile.description1': 'Profesional en Ciberseguridad y Arquitectura de Redes con más de 20 años de trayectoria en el sector industrial. Especialista en la convergencia IT/OT con sólida experiencia en el diseño e implementación del Modelo Purdue para la protección de infraestructuras críticas en Oil & Gas.',
    'profile.description2': 'Experto en defensa activa mediante SIEM (Security Onion), gestión de identidades (IAM) y aseguramiento de la continuidad operativa bajo los estándares IEC 62443, NIST y SOX.',

    // Experience
    'experience.label': 'Trayectoria',
    'experience.title': 'Experience',
    'experience.highlight': 'Laboral',
    'experience.badge.years': '20+ años en el sector industrial',
    'experience.badge.location': 'Oil & Gas · Neuquén · Argentina',
    'experience.badge.tech': 'IT/OT · Cloud · Security · Dev',

    // Experience Jobs ES
    'exp.ypy.period': 'Julio 2025 – Actual',
    'exp.ypy.role': 'Project Manager IT | Cybersecurity Leader | SysAdmin',
    'exp.ypy.badge': 'Actual',
    'exp.ypy.ach.1': 'Políticas de seguridad alineadas a ISO 27001 y NIST',
    'exp.ypy.ach.2': 'SIEM Security Onion + IAM + Firewalls industriales',
    'exp.ypy.ach.3': 'Convergencia IT/OT: protección SCADA y control de procesos',
    'exp.ypy.ach.4': 'Infraestructura híbrida: on-premise + Azure + AWS + VMware',
    'exp.ypy.bullet.1': 'Planificación y ejecución de proyectos tecnológicos bajo metodología PMI con reporte a gerencia',
    'exp.ypy.bullet.2': 'Diseño e implementación de políticas de seguridad alineadas a ISO 27001 y NIST; gestión de riesgos, vulnerabilidades e incidentes',
    'exp.ypy.bullet.3': 'Administración de controles: firewalls, antivirus, IAM y SIEM (Security Onion)',
    'exp.ypy.bullet.4': 'Aseguramiento de la convergencia IT/OT: protección de sistemas SCADA y control de procesos industriales',
    'exp.ypy.bullet.5': 'Supervisión de infraestructuras Edge Computing para garantizar disponibilidad operativa',
    'exp.ypy.bullet.6': 'Administración de servidores Windows/Linux en entornos on-premise, cloud (Azure, AWS) y VMware',
    'exp.ypy.bullet.7': 'Gestión de Active Directory, DNS, DHCP, VPN, backup, recovery y monitoreo 24/7',
    'exp.ops.period': 'Mayo 2013 – Noviembre 2024',
    'exp.ops.role': 'Sr. Network Architect',
    'exp.ops.badge': '11 años',
    'exp.ops.ach.1': '99.9% uptime en sistemas críticos de producción',
    'exp.ops.ach.2': '−30% reducción de incidentes de seguridad',
    'exp.ops.ach.3': '−20% latencia con optimización Cisco / MikroTik',
    'exp.ops.ach.4': '−10h semanales por automatización Python + Power BI',
    'exp.ops.ach.5': '+25% eficiencia: virtualización datacenter vSphere/ESXi',
    'exp.ops.ach.6': 'SIEM Security Onion para detección temprana de intrusiones',
    'exp.ops.bullet.1': 'Diseño de arquitectura de red para sistemas críticos de producción con 99.9% de disponibilidad',
    'exp.ops.bullet.2': 'Implementación de políticas avanzadas de seguridad en redes satelitales y terrestres (−30% incidentes)',
    'exp.ops.bullet.3': 'Actualización y optimización de equipos Cisco y MikroTik (−20% latencia)',
    'exp.ops.bullet.4': 'Automatización de reportes de red con Python y Power BI (−10h semanales)',
    'exp.ops.bullet.5': 'Liderazgo de equipo de 3 ingenieros en virtualización de datacenter (vSphere, ESXi, vCenter, Nexus 1000v)',
    'exp.ops.bullet.6': 'Proyectos de actualización de servidores con equipos globales (−15% downtime)',
    'exp.ops.bullet.7': 'Diseño de anillos de fibra óptica y redes satelitales (VSAT) para telemetría de campo',
    'exp.ops.bullet.8': 'Implementación y mantenimiento de telefonía IP Cisco Unified Manager 8.5',
    'exp.ops.bullet.9': 'Implementación de aceleradores WAN Riverbed para optimización satelital',
    'exp.ops.bullet.10': 'Implementación de plataforma SIEM Security Onion',
    'exp.ops.bullet.11': 'Análisis de datos con Power BI y Python; desarrollo de scripts para análisis de logs',
    'exp.ext.period': 'Marzo 2003 – Mayo 2013',
    'exp.ext.role': 'Business Technology & Infrastructure Manager',
    'exp.ext.badge': '10 años',
    'exp.ext.ach.1': 'Red MPLS: 5 bases + 33 sitios satelitales',
    'exp.ext.ach.2': '−20% recursos físicos con virtualización regional',
    'exp.ext.ach.3': '−20% costos de red vía renegociación de contratos',
    'exp.ext.ach.4': 'HUB Latinoamérica en Bs As: servidores regionales virtualizados',
    'exp.ext.ach.5': 'Cumplimiento SOX implementado para el área de IT',
    'exp.ext.bullet.1': 'Diseño de la red MPLS nacional: 5 bases operativas y 33 sitios satelitales',
    'exp.ext.bullet.2': 'Reducción 20% en recursos físicos: virtualización de servidores regional en Latinoamérica',
    'exp.ext.bullet.3': 'Reducción 20% en costos de red: renegociación de contratos con proveedores clave',
    'exp.ext.bullet.4': 'Estabilidad mejorada 25%: implementación de Veeam, Backup Exec y aceleradores WAN Riverbed',
    'exp.ext.bullet.5': 'Diseño del HUB de Latinoamérica en Buenos Aires virtualizando todos los servidores regionales',
    'exp.ext.bullet.6': 'Implementación del cumplimiento SOX para el área de IT',
    'exp.ext.bullet.7': 'Diseño e implementación de telefonía IP (Cisco Unified Manager 8.5)',
    'exp.ext.bullet.8': 'Implementación de solución de backup corporativo y plan de contingencia',

    // Projects
    'projects.label': 'Impacto Real',
    'projects.title': 'Estudios de',
    'projects.highlight': 'Caso',
    'projects.before': 'Estado Inicial',
    'projects.after': 'Post Intervención',
    'projects.view_project': 'Ver Detalles del Proyecto',
    'projects.case1.title': 'Segmentación OT en Planta de Inyección',
    'projects.case1.company': 'Operadora Petrolera - Neuquén',
    'projects.case1.desc': 'Readecuación de arquitectura de red industrial para cumplir con IEC 62443-3-3, aislando tráfico de control de la red corporativa.',
    'projects.case1.before.1': 'Red plana sin segmentación',
    'projects.case1.before.2': 'Acceso RDP directo desde internet',
    'projects.case1.before.3': 'Protocolos industriales expuestos',
    'projects.case1.after.1': 'Segmentación basada en niveles Purdue',
    'projects.case1.after.2': 'Acceso via DMZ y Bastion Host',
    'projects.case1.after.3': 'IDS industrial (Security Onion)',
    'projects.case1.metric.1': 'Reducción Riesgo',
    'projects.case1.metric.2': 'Aislamiento',
    'projects.case2.title': 'Implementación SIEM Industrial',
    'projects.case2.company': 'Servicios de Energía - Vaca Muerta',
    'projects.case2.desc': 'Centralización de logs de PLCs y Firewalls industriales para detección temprana de intrusiones y fallas operativas.',
    'projects.case2.before.1': 'Logs locales no auditados',
    'projects.case2.before.2': 'Sin visibilidad de tráfico OT',
    'projects.case2.before.3': 'Reactividad ante incidentes',
    'projects.case2.after.1': 'Monitoreo 24/7 centralizado',
    'projects.case2.after.2': 'Alertas de tráfico anómalo',
    'projects.case2.after.3': 'Dashboard de cumplimiento',
    'projects.case2.metric.1': 'Visibilidad',
    'projects.case2.metric.2': 'MTTD',
    'projects.nda': 'Protegido por NDA',
    'projects.iot': 'IoT Industrial',

    // SIEM
    'siem.label': 'Security Operations',
    'siem.title': 'SIEM',
    'siem.highlight': 'Dashboard',
    'siem.map_desc': 'Datos de amenaza en vivo basados en el mapa de Radware Live Threat Map, intervalos de 1 hora.',
    'siem.hover_hint': '▸ Hover sobre un evento ALERT para ver la acción de mitigación',
    'siem.incident_btn': 'Simular Incidente Industrial',
    'siem.incident_btn_active': 'ANALIZANDO EVENTO...',
    'siem.status.connected': 'SISTEMA CONECTADO',
    'siem.status.monitoring': 'MONITOREO EN TIEMPO REAL',
    'siem.ui.auto_response': 'Respuesta automática',
    'siem.ui.mttr': 'MTTR',
    'siem.ui.incident_title': 'INCIDENTE SIMULADO – Purdue Nivel 1',
    'siem.ui.incident_desc': 'Detección de anomalía en dispositivos de campo. El SOC aplica mitigación automática.',
    'siem.ui.event_stream': 'Event Stream – Nivel IT/OT',
    'siem.ui.availability': 'Disponibilidad por Zona Purdue',
    'siem.ui.threat_summary': 'Resumen de Amenazas',
    'siem.ui.operational_kpis': 'KPIs Operativos',
    'siem.ui.top_attackers': 'Top Atacantes',
    'siem.ui.top_attacked': 'Top Atacados',
    'siem.ui.attack_vectors': 'Vectores de Ataque',
    
    // SIEM Data ES
    'siem.kpi.uptime': 'Uptime Red Industrial',
    'siem.kpi.latency': 'Latencia Promedio OT',
    'siem.kpi.blocked': 'Ataques Bloqueados (24h)',
    'siem.kpi.alerts': 'Alertas Críticas Activas',
    'siem.zone.field': 'Nivel 1 – Dispositivos de Campo',
    'siem.zone.control': 'Nivel 2 – Control de Procesos',
    'siem.zone.operations': 'Nivel 3 – Operaciones de Planta',
    'siem.zone.idmz': 'DMZ Industrial',
    'siem.zone.enterprise': 'Nivel 4/5 – Red Corporativa',

    // Audit
    'audit.label': 'CUMPLIMIENTO ESTRATÉGICO',
    'audit.title': 'Governance &',
    'audit.highlight': 'Audit Hub',
    'audit.stats.score': 'Score de Seguridad',
    'audit.stats.controls': 'Controles Validados',
    'audit.stats.risk_gap': 'Brecha de Riesgo',
    'audit.stats.next_cycle': 'Próximo Ciclo',
    'audit.stats.global_compliance': 'Compliance Global',
    'audit.severity': 'Severidad',
    'audit.status': 'Estado',
    'audit.tab.compliance': 'ESTADO DE CUMPLIMIENTO',
    'audit.tab.findings': 'HALLAZGOS DE AUDITORÍA',
    'audit.ui.monitoring': 'MONITOREO DE MARCOS REGULATORIOS',
    'audit.ui.health_by_domain': 'SALUD POR DOMINIO',
    'audit.ui.score': 'SCORE',
    'audit.ui.metric_note': '* Métrica basada en la efectividad operativa de los controles implementados en Nivel 0-3.',
    'audit.ui.filter_severity': 'Filtrar por Severidad:',
    'audit.ui.report': 'Reporte',
    'audit.ui.severity': 'Severidad',
    'audit.ui.status': 'Estado',
    'audit.ui.control_asset': 'Control / Activo',
    'audit.ui.action': 'Acción',
    'audit.ui.impact': 'Impacto en Negocio',
    'audit.ui.remediation_plan': 'Plan de Remediación',
    'audit.ui.technical_evidence': 'Evidencia Técnica (Log)',
    'audit.ui.owner': 'Propietario',
    'audit.ui.reference': 'Referencia',
    'audit.ui.last_review': 'ÚLTIMA REVISIÓN',
    'audit.ui.analyst': 'ANALISTA',
    'audit.ui.operational_compliance': 'Cumplimiento Operativo',
    'audit.ui.integrated_strategy': 'Estrategia Integrada',
    'audit.ui.close': 'Cerrar',
    'audit.ui.details': 'Detalles',
    'audit.severity.high': 'Alta',
    'audit.severity.medium': 'Media',
    'audit.severity.low': 'Baja',
    'audit.severity.all': 'Todos',
    'audit.status.remediated': 'Remediado',
    'audit.status.in_progress': 'En Progreso',
    'audit.status.planned': 'Planificado',

    // Audit Data ES
    'audit.marco.iso.desc': 'Sistema de Gestión de Seguridad de la Información (SGSI).',
    'audit.marco.iec.desc': 'Seguridad para sistemas de control y automatización industrial (IACS).',
    'audit.marco.nist.desc': 'Marco de Ciberseguridad para infraestructuras críticas.',
    'audit.marco.gdpr.desc': 'Protección de datos y privacidad industrial.',
    'audit.domain.id': 'Identificación',
    'audit.domain.prot': 'Protección',
    'audit.domain.det': 'Detección',
    'audit.domain.resp': 'Respuesta',
    'audit.domain.rec': 'Recuperación',
    'audit.finding.001.desc': 'Falta de autenticación multifactor (MFA) en HMI de zona de procesos.',
    'audit.finding.001.remediation': 'Implementación de PAM con integración Duo Security para acceso a activos críticos.',
    'audit.finding.001.impact': 'Riesgo Crítico de acceso no autorizado a sistemas de control de planta (SCADA).',
    'audit.finding.002.desc': 'Reglas de firewall permisivas entre Nivel 3 y Nivel 4 (Purdue).',
    'audit.finding.002.remediation': 'Reconfiguración de IDS Inline y Micro-segmentación mediante FortiGate OT.',
    'audit.finding.002.impact': 'Movimiento lateral potencial entre redes IT y OT, exponiendo PLCs.',
    'audit.finding.003.desc': 'Dispositivos IoT no inventariados en VLAN de servicios generales.',
    'audit.finding.003.remediation': 'Despliegue de Claroty CTD para visibilidad pasiva de activos OT.',
    'audit.finding.003.impact': 'Pérdida parcial de visibilidad en el inventario de activos no críticos.',
    'audit.finding.004.desc': 'Logs históricos de PLC guardados en texto plano en historiador.',
    'audit.finding.004.remediation': 'Encriptación AES-256 en base de datos de historiador y firma digital.',
    'audit.finding.004.impact': 'Posible manipulación de registros históricos de producción (Data Integrity).',

    // Architecture
    'arch.label': 'Visión sistémica',
    'arch.title': 'Mapa de Convergencia IT/OT',
    'arch.highlight': 'Modelo Purdue',
    'arch.description': 'Estructura jerárquica para la segmentación de redes industriales y aseguramiento de procesos críticos.',
    'arch.interactive_desc': 'Mapa interactivo de convergencia IT/OT inspirado en el Modelo Purdue. Haz clic en un nodo para resaltar dependencias entre SCADA, firewalls industriales, virtualización y controles de seguridad.',
    'arch.domain.ot': 'Capa Inferior OT',
    'arch.domain.infra': 'Capa Media Infraestructura',
    'arch.domain.security': 'Capa Superior Seguridad',
    'arch.domain.items.virt': 'Virtualización',
    'arch.domain.items.networks': 'Redes Cisco',
    'arch.domain.items.firewalls': 'Firewalls Industriales',
    'arch.domain.items.strategy': 'Estrategia GRC',
    
    // Purdue Nodes ES
    'arch.purdue.level.security': 'Capa Superior: Seguridad & Gestión',
    'arch.purdue.level.infra': 'Capa Media: Infraestructura IT/OT',
    'arch.purdue.level.ot': 'Capa Inferior: Control & Operaciones (OT)',
    'arch.purdue.nodes.siem.label': 'SIEM / SOC',
    'arch.purdue.nodes.siem.desc': 'Monitorización continua de eventos y respuesta ante incidentes.',
    'arch.purdue.nodes.nist.label': 'NIST CSF',
    'arch.purdue.nodes.nist.desc': 'Marco de ciberseguridad para infraestructuras críticas.',
    'arch.purdue.nodes.grc.label': 'Estrategia GRC',
    'arch.purdue.nodes.grc.desc': 'Gobierno, Riesgo y Cumplimiento normativo industrial.',
    'arch.purdue.nodes.virtual.label': 'Virtualización',
    'arch.purdue.nodes.virtual.desc': 'Servidores vSphere para control industrial de alta disponibilidad.',
    'arch.purdue.nodes.firewall.label': 'Firewalls Industriales',
    'arch.purdue.nodes.firewall.desc': 'Segmentación perimetral y protección de activos críticos.',
    'arch.purdue.nodes.idmz.label': 'Industrial DMZ',
    'arch.purdue.nodes.idmz.desc': 'Zona desmilitarizada para intercambio seguro de datos IT/OT.',
    'arch.purdue.nodes.scada.label': 'SCADA / HMI',
    'arch.purdue.nodes.scada.desc': 'Supervisión de procesos y control de interfaz humano-máquina.',
    'arch.purdue.nodes.plc.label': 'PLC / RTU',
    'arch.purdue.nodes.plc.desc': 'Controladores lógicos programables y terminales remotas.',
    'arch.purdue.nodes.plant.label': 'Nivel 0-2 (Planta)',
    'arch.purdue.nodes.plant.desc': 'Instrumentación, sensores de campo y actuadores de proceso.',

    // Stack
    'stack.label': 'Ecosistema Tecnológico',
    'stack.title': 'Herramientas &',
    'stack.highlight': 'Stack',
    'stack.cat.security': 'Seguridad',
    'stack.title.security': 'Ciberseguridad Industrial',
    'stack.cat.network': 'Redes',
    'stack.title.network': 'Infraestructura & Conectividad',
    'stack.cat.cloud': 'Cloud & Virtualización',
    'stack.title.cloud': 'Plataformas & Servidores',
    'stack.cat.ot': 'OT / Industrial',
    'stack.title.ot': 'Control Systems',
    'stack.cat.dev': 'Desarrollo',
    'stack.title.dev': 'Web & Full-Stack',
    'stack.cat.ai': 'Automatización & Datos',
    'stack.title.ai': 'Operational Intelligence',
    'stack.tag.siem': 'Security Onion (SIEM)',
    'stack.tag.firewalls': 'Firewalls',
    'stack.tag.iam': 'IAM',
    'stack.tag.iec': 'IEC 62443',
    'stack.tag.nist': 'NIST CSF',
    'stack.tag.iso': 'ISO 27001',
    'stack.tag.sox': 'SOX',
    'stack.tag.purdue': 'Modelo Purdue',
    'stack.tag.ir': 'Respuesta ante Incidentes',
    'stack.tag.networks': 'Redes Cisco CCNA',
    'stack.tag.mpls': 'MPLS',
    'stack.tag.mikrotik': 'MikroTik',
    'stack.tag.vsat': 'VSAT',
    'stack.tag.wan': 'Riverbed WAN',
    'stack.tag.vpn': 'VPN',
    'stack.tag.fiber': 'Fibra Óptica',
    'stack.tag.dns': 'DNS / DHCP',
    'stack.tag.azure': 'Microsoft Azure',
    'stack.tag.aws': 'AWS',
    'stack.tag.vmware': 'VMware vSphere',
    'stack.tag.esxi': 'ESXi',
    'stack.tag.vcenter': 'vCenter',
    'stack.tag.windows': 'Windows Server 2003–2022',
    'stack.tag.ad': 'Active Directory',
    'stack.tag.linux': 'Linux',
    'stack.tag.scada': 'SCADA',
    'stack.tag.modbus': 'Modbus',
    'stack.tag.opc': 'OPC UA',
    'stack.tag.dnp3': 'DNP3',
    'stack.tag.edge': 'Edge Computing',
    'stack.tag.veeam': 'Veeam Backup',
    'stack.tag.industrial_control': 'Control Industrial',
    'stack.tag.nextjs': 'Next.js 14',
    'stack.tag.react': 'React.js',
    'stack.tag.tailwind': 'Tailwind CSS',
    'stack.tag.js': 'JavaScript ES6+',
    'stack.tag.ts': 'TypeScript',
    'stack.tag.cicd': 'CI/CD',
    'stack.tag.vercel': 'Vercel',
    'stack.tag.seo': 'SEO Técnico',
    'stack.tag.python': 'Python',
    'stack.tag.powerbi': 'Power BI',
    'stack.tag.powershell': 'PowerShell',
    'stack.tag.kpi': 'Dashboards KPI',
    'stack.tag.data_analysis': 'Análisis de datos',
    'stack.tag.reports': 'Reportes automáticos',

    // Certs
    'certs.label': 'Validación Profesional',
    'certs.title': 'Certificaciones &',
    'certs.highlight': 'Logros',
    'certs.analyst': 'Analista de sistemas – UNCO',
    'certs.pm': 'Project Management & IEC 62443 – Universidad Siglo 21',
    'certs.english': 'Inglés B2 – Intermedio Alto',

    // Blog
    'blog.label': 'Pensamiento Técnico',
    'blog.title': 'Inteligencia',
    'blog.highlight': 'IT/OT',
    'blog.description': 'Análisis y reflexiones sobre la convergencia de redes, ciberseguridad industrial y el futuro de la infraestructura crítica.',
    'blog.read_more': 'Leer más',
    'blog.view_all': 'Ver todos los artículos',
    'blog.post1.title': 'Implementando IEC 62443 en la Cuenca Neuquina',
    'blog.post1.excerpt': 'Desafíos y estrategias para la segmentación de redes industriales en yacimientos no convencionales.',
    'blog.post1.readTime': '5 min',
    'blog.post1.tag': 'Vaca Muerta',
    'blog.post2.title': 'SIEM para Convergencia IT/OT: Más allá del Firewall',
    'blog.post2.excerpt': 'Cómo Security Onion y reglas personalizadas pueden detectar anomalías en protocolos Modbus y DNP3.',
    'blog.post2.readTime': '7 min',
    'blog.post2.tag': 'Security Onion',
    'blog.post3.title': 'NIST CSF en Infraestructuras Críticas',
    'blog.post3.excerpt': 'Guía práctica para la autoevaluación de madurez en ciberseguridad para empresas de servicios petroleros.',
    'blog.post3.readTime': '6 min',
    'blog.post3.tag': 'Compliance',

    // AI Consultant
    'ai.welcome': 'Hola, soy Nacho Assistant, el consultor IA de Juan. ¿En qué puedo ayudarte hoy sobre su perfil IT/OT?',
    'ai.placeholder': 'Escribe tu consulta sobre Juan...',
    'ai.subtitle': 'Arquitecto IT/OT IA',
    'ai.footer': 'Responde basado en la experiencia de Juan en IT/OT',
    'ai.error': 'Actualmente tengo problemas de conexión. Por favor, intenta de nuevo más tarde.',
    'ai.close': 'Cerrar chat',

    // Contact
    'contact.label': 'Conexión Segura',
    'contact.title': 'Contacto',
    'contact.highlight': 'Directo',
    'contact.description': 'Especializado en proyectos de alta criticidad en entornos industriales Oil & Gas. Disponible para consultoría, arquitectura IT/OT, ciberseguridad y liderazgo técnico.',
    'contact.availability': 'Disponible para proyectos de alta criticidad',
    'contact.form.title': 'Iniciar conversación',
    'contact.form.subtitle': 'Contame sobre tu proyecto para darte una respuesta más precisa.',
    'contact.form.name': 'Nombre Completo',
    'contact.form.email': 'Email Corporativo',
    'contact.form.company': 'Empresa / Organización',
    'contact.form.type': 'Tipo de proyecto *',
    'contact.form.type.placeholder': 'Seleccioná el tipo de proyecto…',
    'contact.form.message': 'Mensaje / Requerimiento Técnico',
    'contact.form.message.placeholder': 'Contame brevemente el contexto (sector, urgencia, alcance)…',
    'contact.form.send': 'Enviar Protocolo de Contacto',
    'contact.form.sending': 'Enviando…',
    'contact.form.success': '¡Mensaje enviado!',
    'contact.form.success_msg': 'Respondo en menos de 24 horas hábiles.',
    'contact.form.footer': 'Respuesta en < 24h · Sin spam · Datos confidenciales',
    'contact.download_cv': 'Descargar CV',
    'contact.type.audit': 'Auditoría de Seguridad OT/IT',
    'contact.type.siem': 'Implementación SIEM (Security Onion)',
    'contact.type.arch': 'Diseño Arquitectura IT/OT (Modelo Purdue)',
    'contact.type.network': 'Infraestructura de Red – Oil & Gas',
    'contact.type.cloud': 'Virtualización y Cloud (Azure/VMware)',
    'contact.type.automation': 'Automatización Python / Power BI',
    'contact.type.compliance': 'Consultoría IEC 62443 / NIST / ISO 27001',
    'contact.type.dev': 'Desarrollo Web (Next.js / Full Stack)',
    'contact.type.other': 'Otro',

    // Footer
    'footer.built_with': 'Construido con Next.js 14 · Framer Motion · Three.js',
  },
  en: {
    // Nav
    'nav.profile': 'Profile',
    'nav.architecture': 'Architecture',
    'nav.experience': 'Experience',
    'nav.siem': 'SIEM',
    'nav.audit': 'Audit',
    'nav.blog': 'Intelligence',
    'nav.stack': 'Stack',
    'nav.projects': 'Case Studies',
    'nav.contact': 'Contact',

    // Hero
    'hero.title.first': 'Juan Felipe',
    'hero.title.last': 'Palacios',
    'hero.subtitle': 'Project Manager IT | Cybersecurity Leader | SysAdmin',
    'hero.role': 'IT/OT Cybersecurity Architect',
    'hero.tagline': 'Digital resilience for critical infrastructures and the Oil & Gas sector.',
    'hero.cta.history': 'Critical History',
    'hero.cta.architecture': 'OT Architecture',
    'hero.system_active': 'System Active',
    'hero.protocol': 'IT/OT Protocol · Cybersecurity',
    'hero.role_details': 'Project Manager IT | Cybersecurity Leader | SysAdmin',
    'hero.scroll': 'Scroll System',

    // Perfil
    'profile.label': 'About me',
    'profile.title': 'Professional',
    'profile.highlight': 'Profile',
    'profile.description1': 'Cybersecurity and Network Architecture professional with over 20 years of experience in the industrial sector. Specialist in IT/OT convergence with solid experience in the design and implementation of the Purdue Model for critical infrastructure protection in Oil & Gas.',
    'profile.description2': 'Expert in active defense through SIEM (Security Onion), Identity and Access Management (IAM), and ensuring operational continuity under IEC 62443, NIST, and SOX standards.',

    // Experience
    'experience.label': 'Career Path',
    'experience.title': 'Work',
    'experience.highlight': 'Experience',
    'experience.badge.years': '20+ years in the industrial sector',
    'experience.badge.location': 'Oil & Gas · Neuquén · Argentina',
    'experience.badge.tech': 'IT/OT · Cloud · Security · Dev',

    // Experience Jobs EN
    'exp.ypy.period': 'July 2025 – Present',
    'exp.ypy.role': 'IT Project Manager | Cybersecurity Leader | SysAdmin',
    'exp.ypy.badge': 'Current',
    'exp.ypy.ach.1': 'Security policies aligned with ISO 27001 and NIST',
    'exp.ypy.ach.2': 'SIEM Security Onion + IAM + Industrial Firewalls',
    'exp.ypy.ach.3': 'IT/OT Convergence: SCADA protection and process control',
    'exp.ypy.ach.4': 'Hybrid infrastructure: on-premise + Azure + AWS + VMware',
    'exp.ypy.bullet.1': 'Planning and execution of technological projects under PMI methodology with reporting to management',
    'exp.ypy.bullet.2': 'Design and implementation of security policies aligned with ISO 27001 and NIST; risk, vulnerability, and incident management',
    'exp.ypy.bullet.3': 'Management of controls: firewalls, antivirus, IAM, and SIEM (Security Onion)',
    'exp.ypy.bullet.4': 'Ensuring IT/OT convergence: protection of SCADA systems and industrial process control',
    'exp.ypy.bullet.5': 'Supervision of Edge Computing infrastructures to guarantee operational availability',
    'exp.ypy.bullet.6': 'Administration of Windows/Linux servers in on-premise, cloud (Azure, AWS), and VMware environments',
    'exp.ypy.bullet.7': 'Management of Active Directory, DNS, DHCP, VPN, backup, recovery, and 24/7 monitoring',
    'exp.ops.period': 'May 2013 – November 2024',
    'exp.ops.role': 'Sr. Network Architect',
    'exp.ops.badge': '11 years',
    'exp.ops.ach.1': '99.9% uptime in critical production systems',
    'exp.ops.ach.2': '−30% reduction in security incidents',
    'exp.ops.ach.3': '−20% latency with Cisco / MikroTik optimization',
    'exp.ops.ach.4': '−10h weekly through Python + Power BI automation',
    'exp.ops.ach.5': '+25% efficiency: vSphere/ESXi datacenter virtualization',
    'exp.ops.ach.6': 'SIEM Security Onion for early intrusion detection',
    'exp.ops.bullet.1': 'Network architecture design for critical production systems with 99.9% availability',
    'exp.ops.bullet.2': 'Implementation of advanced security policies in satellite and terrestrial networks (−30% incidents)',
    'exp.ops.bullet.3': 'Upgrade and optimization of Cisco and MikroTik equipment (−20% latency)',
    'exp.ops.bullet.4': 'Network reporting automation with Python and Power BI (−10h weekly)',
    'exp.ops.bullet.5': 'Leading a team of 3 engineers in datacenter virtualization (vSphere, ESXi, vCenter, Nexus 1000v)',
    'exp.ops.bullet.6': 'Server upgrade projects with global equipment (−15% downtime)',
    'exp.ops.bullet.7': 'Design of fiber optic rings and satellite networks (VSAT) for field telemetry',
    'exp.ops.bullet.8': 'Implementation and maintenance of Cisco Unified Manager 8.5 IP telephony',
    'exp.ops.bullet.9': 'Implementation of Riverbed WAN accelerators for satellite optimization',
    'exp.ops.bullet.10': 'Implementation of SIEM Security Onion platform',
    'exp.ops.bullet.11': 'Data analysis with Power BI and Python; development of scripts for log analysis',
    'exp.ext.period': 'March 2003 – May 2013',
    'exp.ext.role': 'Business Technology & Infrastructure Manager',
    'exp.ext.badge': '10 years',
    'exp.ext.ach.1': 'MPLS network: 5 bases + 33 satellite sites',
    'exp.ext.ach.2': '−20% physical resources with regional virtualization',
    'exp.ext.ach.3': '−20% network costs via contract renegotiation',
    'exp.ext.ach.4': 'Latin America HUB in Buenos Aires: virtualized regional servers',
    'exp.ext.ach.5': 'SOX compliance implemented for IT area',
    'exp.ext.bullet.1': 'Design of the national MPLS network: 5 operational bases and 33 satellite sites',
    'exp.ext.bullet.2': '20% reduction in physical resources: regional server virtualization in Latin America',
    'exp.ext.bullet.3': '20% reduction in network costs: contract renegotiation with key providers',
    'exp.ext.bullet.4': 'Improved stability by 25%: implementation of Veeam, Backup Exec, and Riverbed WAN accelerators',
    'exp.ext.bullet.5': 'Design of the Latin America HUB in Buenos Aires virtualizing all regional servers',
    'exp.ext.bullet.6': 'Implementation of SOX compliance for the IT area',
    'exp.ext.bullet.7': 'Design and implementation of IP telephony (Cisco Unified Manager 8.5)',
    'exp.ext.bullet.8': 'Implementation of corporate backup solution and contingency plan',

    // Projects
    'projects.label': 'Real Impact',
    'projects.title': 'Case',
    'projects.highlight': 'Studies',
    'projects.before': 'Initial State',
    'projects.after': 'Post Intervention',
    'projects.view_project': 'View Project Details',
    'projects.case1.title': 'OT Segmentation in Injection Plant',
    'projects.case1.company': 'Oil Operator - Neuquén',
    'projects.case1.desc': 'Industrial network architecture redesign to comply with IEC 62443-3-3, isolating control traffic from the corporate network.',
    'projects.case1.before.1': 'Flat network without segmentation',
    'projects.case1.before.2': 'Direct RDP access from internet',
    'projects.case1.before.3': 'Exposed industrial protocols',
    'projects.case1.after.1': 'Segmentation based on Purdue levels',
    'projects.case1.after.2': 'Access via DMZ and Bastion Host',
    'projects.case1.after.3': 'Industrial IDS (Security Onion)',
    'projects.case1.metric.1': 'Risk Reduction',
    'projects.case1.metric.2': 'Isolation',
    'projects.case2.title': 'Industrial SIEM Implementation',
    'projects.case2.company': 'Energy Services - Vaca Muerta',
    'projects.case2.desc': 'Centralization of PLC and Industrial Firewall logs for early detection of intrusions and operational failures.',
    'projects.case2.before.1': 'Unaudited local logs',
    'projects.case2.before.2': 'No OT traffic visibility',
    'projects.case2.before.3': 'Reactive response to incidents',
    'projects.case2.after.1': 'Centralized 24/7 monitoring',
    'projects.case2.after.2': 'Anomalous traffic alerts',
    'projects.case2.after.3': 'Compliance Dashboard',
    'projects.case2.metric.1': 'Visibility',
    'projects.case2.metric.2': 'MTTD',
    'projects.nda': 'NDA Protected',
    'projects.iot': 'Industrial IoT',

    // SIEM
    'siem.label': 'Security Operations',
    'siem.title': 'SIEM',
    'siem.highlight': 'Dashboard',
    'siem.map_desc': 'Live threat data based on Radware Live Threat Map, 1-hour intervals.',
    'siem.hover_hint': '▸ Hover over an ALERT event to see mitigation action',
    'siem.incident_btn': 'Simulate Industrial Incident',
    'siem.incident_btn_active': 'ANALIZANDO EVENTO...',
    'siem.status.connected': 'SYSTEM CONNECTED',
    'siem.status.monitoring': 'REAL-TIME MONITORING',
    'siem.ui.auto_response': 'Automatic response',
    'siem.ui.mttr': 'MTTR',
    'siem.ui.incident_title': 'SIMULATED INCIDENT – Purdue Level 1',
    'siem.ui.incident_desc': 'Anomaly detection in field devices. SOC applies automatic mitigation.',
    'siem.ui.event_stream': 'Event Stream – IT/OT Level',
    'siem.ui.availability': 'Purdue Zone Availability',
    'siem.ui.threat_summary': 'Threat Summary',
    'siem.ui.operational_kpis': 'Operational KPIs',
    'siem.ui.top_attackers': 'Top Attackers',
    'siem.ui.top_attacked': 'Top Attacked',
    'siem.ui.attack_vectors': 'Attack Vectors',

    // SIEM Data EN
    'siem.kpi.uptime': 'Industrial Network Uptime',
    'siem.kpi.latency': 'OT Average Latency',
    'siem.kpi.blocked': 'Blocked Attacks (24h)',
    'siem.kpi.alerts': 'Active Critical Alerts',
    'siem.zone.field': 'Level 1 – Field Devices',
    'siem.zone.control': 'Level 2 – Process Control',
    'siem.zone.operations': 'Level 3 – Plant Operations',
    'siem.zone.idmz': 'Industrial DMZ',
    'siem.zone.enterprise': 'Level 4/5 – Enterprise Network',

    // Audit
    'audit.label': 'STRATEGIC COMPLIANCE',
    'audit.title': 'Governance &',
    'audit.highlight': 'Audit Hub',
    'audit.stats.score': 'Security Score',
    'audit.stats.controls': 'Validated Controls',
    'audit.stats.risk_gap': 'Risk Gap',
    'audit.stats.next_cycle': 'Next Cycle',
    'audit.stats.global_compliance': 'Global Compliance',
    'audit.severity': 'Severity',
    'audit.status': 'Status',
    'audit.tab.compliance': 'COMPLIANCE STATUS',
    'audit.tab.findings': 'AUDIT FINDINGS',
    'audit.ui.monitoring': 'REGULATORY FRAMEWORK MONITORING',
    'audit.ui.health_by_domain': 'HEALTH BY DOMAIN',
    'audit.ui.score': 'SCORE',
    'audit.ui.metric_note': '* Metric based on the operational effectiveness of controls implemented in Level 0-3.',
    'audit.ui.filter_severity': 'Filter by Severity:',
    'audit.ui.report': 'Report',
    'audit.ui.severity': 'Severity',
    'audit.ui.status': 'Status',
    'audit.ui.control_asset': 'Control / Asset',
    'audit.ui.action': 'Action',
    'audit.ui.impact': 'Business Impact',
    'audit.ui.remediation_plan': 'Remediation Plan',
    'audit.ui.technical_evidence': 'Technical Evidence (Log)',
    'audit.ui.owner': 'Owner',
    'audit.ui.reference': 'Reference',
    'audit.ui.last_review': 'LAST REVIEW',
    'audit.ui.analyst': 'ANALYST',
    'audit.ui.operational_compliance': 'Operational Compliance',
    'audit.ui.integrated_strategy': 'Integrated Strategy',
    'audit.ui.close': 'Close',
    'audit.ui.details': 'Details',
    'audit.severity.high': 'High',
    'audit.severity.medium': 'Medium',
    'audit.severity.low': 'Low',
    'audit.severity.all': 'All',
    'audit.status.remediated': 'Remediated',
    'audit.status.in_progress': 'In Progress',
    'audit.status.planned': 'Planned',

    // Audit Data EN
    'audit.marco.iso.desc': 'Information Security Management System (ISMS).',
    'audit.marco.iec.desc': 'Security for industrial automation and control systems (IACS).',
    'audit.marco.nist.desc': 'Cybersecurity Framework for critical infrastructures.',
    'audit.marco.gdpr.desc': 'Data protection and industrial privacy.',
    'audit.domain.id': 'Identify',
    'audit.domain.prot': 'Protect',
    'audit.domain.det': 'Detect',
    'audit.domain.resp': 'Respond',
    'audit.domain.rec': 'Recover',
    'audit.finding.001.desc': 'Lack of multi-factor authentication (MFA) on process zone HMI.',
    'audit.finding.001.remediation': 'PAM implementation with Duo Security integration for access to critical assets.',
    'audit.finding.001.impact': 'Critical risk of unauthorized access to plant control systems (SCADA).',
    'audit.finding.002.desc': 'Permissive firewall rules between Level 3 and Level 4 (Purdue).',
    'audit.finding.002.remediation': 'IDS Inline reconfiguration and Micro-segmentation via FortiGate OT.',
    'audit.finding.002.impact': 'Potential lateral movement between IT and OT networks, exposing PLCs.',
    'audit.finding.003.desc': 'Uninventoried IoT devices in general services VLAN.',
    'audit.finding.003.remediation': 'Claroty CTD deployment for passive OT asset visibility.',
    'audit.finding.003.impact': 'Partial loss of visibility in the inventory of non-critical assets.',
    'audit.finding.004.desc': 'Historical PLC logs saved in plain text in historian.',
    'audit.finding.004.remediation': 'AES-256 encryption in historian database and digital signature.',
    'audit.finding.004.impact': 'Possible manipulation of historical production records (Data Integrity).',

    // Architecture
    'arch.label': 'Systemic Vision',
    'arch.title': 'IT/OT Convergence Map',
    'arch.highlight': 'Purdue Model',
    'arch.description': 'Hierarchical structure for industrial network segmentation and critical process assurance.',
    'arch.interactive_desc': 'Interactive IT/OT convergence map inspired by the Purdue Model. Click a node to highlight dependencies between SCADA, industrial firewalls, virtualization, and security controls.',
    'arch.domain.ot': 'Lower OT Layer',
    'arch.domain.infra': 'Middle Infrastructure Layer',
    'arch.domain.security': 'Upper Security Layer',
    'arch.domain.items.virt': 'Virtualization',
    'arch.domain.items.networks': 'Cisco Networks',
    'arch.domain.items.firewalls': 'Industrial Firewalls',
    'arch.domain.items.strategy': 'GRC Strategy',
    
    // Purdue Nodes EN
    'arch.purdue.level.security': 'Upper Layer: Security & Management',
    'arch.purdue.level.infra': 'Middle Layer: IT/OT Infrastructure',
    'arch.purdue.level.ot': 'Lower Layer: Control & Operations (OT)',
    'arch.purdue.nodes.siem.label': 'SIEM / SOC',
    'arch.purdue.nodes.siem.desc': 'Continuous event monitoring and incident response.',
    'arch.purdue.nodes.nist.label': 'NIST CSF',
    'arch.purdue.nodes.nist.desc': 'Cybersecurity framework for critical infrastructures.',
    'arch.purdue.nodes.grc.label': 'GRC Strategy',
    'arch.purdue.nodes.grc.desc': 'Industrial Governance, Risk, and Compliance.',
    'arch.purdue.nodes.virtual.label': 'Virtualization',
    'arch.purdue.nodes.virtual.desc': 'High-availability vSphere servers for industrial control.',
    'arch.purdue.nodes.firewall.label': 'Industrial Firewalls',
    'arch.purdue.nodes.firewall.desc': 'Perimeter segmentation and critical asset protection.',
    'arch.purdue.nodes.idmz.label': 'Industrial DMZ',
    'arch.purdue.nodes.idmz.desc': 'Demilitarized zone for secure IT/OT data exchange.',
    'arch.purdue.nodes.scada.label': 'SCADA / HMI',
    'arch.purdue.nodes.scada.desc': 'Process supervision and human-machine interface control.',
    'arch.purdue.nodes.plc.label': 'PLC / RTU',
    'arch.purdue.nodes.plc.desc': 'Programmable logic controllers and remote terminals.',
    'arch.purdue.nodes.plant.label': 'Level 0-2 (Plant)',
    'arch.purdue.nodes.plant.desc': 'Instrumentation, field sensors, and process actuators.',

    // Stack
    'stack.label': 'Technology Ecosystem',
    'stack.title': 'Tools &',
    'stack.highlight': 'Stack',
    'stack.cat.security': 'Security',
    'stack.title.security': 'Industrial Cybersecurity',
    'stack.cat.network': 'Networks',
    'stack.title.network': 'Infrastructure & Connectivity',
    'stack.cat.cloud': 'Cloud & Virtualization',
    'stack.title.cloud': 'Platforms & Servers',
    'stack.cat.ot': 'OT / Industrial',
    'stack.title.ot': 'Control Systems',
    'stack.cat.dev': 'Development',
    'stack.title.dev': 'Web & Full-Stack',
    'stack.cat.ai': 'Automation & Data',
    'stack.title.ai': 'Operational Intelligence',
    'stack.tag.siem': 'Security Onion (SIEM)',
    'stack.tag.firewalls': 'Firewalls',
    'stack.tag.iam': 'IAM',
    'stack.tag.iec': 'IEC 62443',
    'stack.tag.nist': 'NIST CSF',
    'stack.tag.iso': 'ISO 27001',
    'stack.tag.sox': 'SOX',
    'stack.tag.purdue': 'Purdue Model',
    'stack.tag.ir': 'Incident Response',
    'stack.tag.networks': 'Cisco Networks CCNA',
    'stack.tag.mpls': 'MPLS',
    'stack.tag.mikrotik': 'MikroTik',
    'stack.tag.vsat': 'VSAT',
    'stack.tag.wan': 'Riverbed WAN',
    'stack.tag.vpn': 'VPN',
    'stack.tag.fiber': 'Fiber Optics',
    'stack.tag.dns': 'DNS / DHCP',
    'stack.tag.azure': 'Microsoft Azure',
    'stack.tag.aws': 'AWS',
    'stack.tag.vmware': 'VMware vSphere',
    'stack.tag.esxi': 'ESXi',
    'stack.tag.vcenter': 'vCenter',
    'stack.tag.windows': 'Windows Server 2003–2022',
    'stack.tag.ad': 'Active Directory',
    'stack.tag.linux': 'Linux',
    'stack.tag.scada': 'SCADA',
    'stack.tag.modbus': 'Modbus',
    'stack.tag.opc': 'OPC UA',
    'stack.tag.dnp3': 'DNP3',
    'stack.tag.edge': 'Edge Computing',
    'stack.tag.veeam': 'Veeam Backup',
    'stack.tag.industrial_control': 'Industrial Control',
    'stack.tag.nextjs': 'Next.js 14',
    'stack.tag.react': 'React.js',
    'stack.tag.tailwind': 'Tailwind CSS',
    'stack.tag.js': 'JavaScript ES6+',
    'stack.tag.ts': 'TypeScript',
    'stack.tag.cicd': 'CI/CD',
    'stack.tag.vercel': 'Vercel',
    'stack.tag.seo': 'Technical SEO',
    'stack.tag.python': 'Python',
    'stack.tag.powerbi': 'Power BI',
    'stack.tag.powershell': 'PowerShell',
    'stack.tag.kpi': 'KPI Dashboards',
    'stack.tag.data_analysis': 'Data Analysis',
    'stack.tag.reports': 'Automatic Reports',

    // Certs
    'certs.label': 'Professional Validation',
    'certs.title': 'Certifications &',
    'certs.highlight': 'Achievements',
    'certs.analyst': 'Systems Analyst – UNCO',
    'certs.pm': 'Project Management & IEC 62443 – Siglo 21 University',
    'certs.english': 'English B2 – Upper Intermediate',

    // Blog
    'blog.label': 'Technical Thinking',
    'blog.title': 'IT/OT',
    'blog.highlight': 'Intelligence',
    'blog.description': 'Analysis and reflections on network convergence, industrial cybersecurity, and the future of critical infrastructure.',
    'blog.read_more': 'Read more',
    'blog.view_all': 'View all articles',
    'blog.post1.title': 'Implementing IEC 62443 in the Neuquén Basin',
    'blog.post1.excerpt': 'Challenges and strategies for industrial network segmentation in unconventional reservoirs.',
    'blog.post1.readTime': '5 min',
    'blog.post1.tag': 'Vaca Muerta',
    'blog.post2.title': 'SIEM for IT/OT Convergence: Beyond the Firewall',
    'blog.post2.excerpt': 'How Security Onion and custom rules can detect anomalies in Modbus and DNP3 protocols.',
    'blog.post2.readTime': '7 min',
    'blog.post2.tag': 'Security Onion',
    'blog.post3.title': 'NIST CSF in Critical Infrastructures',
    'blog.post3.excerpt': 'Practical guide for cybersecurity maturity self-assessment for oil service companies.',
    'blog.post3.readTime': '6 min',
    'blog.post3.tag': 'Compliance',

    // AI Consultant
    'ai.welcome': 'Hi, I am Nacho Assistant, Juan\'s AI consultant. How can I help you today regarding his IT/OT profile?',
    'ai.placeholder': 'Write your query about Juan...',
    'ai.subtitle': 'AI IT/OT Architect',
    'ai.footer': 'Responds based on Juan\'s IT/OT experience',
    'ai.error': 'I currently have connection problems. Please try again later.',
    'ai.close': 'Close chat',

    // Contact
    'contact.label': 'Secure Connection',
    'contact.title': 'Direct',
    'contact.highlight': 'Contact',
    'contact.description': 'Specialized in high-criticality projects in industrial Oil & Gas environments. Available for consultancy, IT/OT architecture, cybersecurity, and technical leadership.',
    'contact.availability': 'Available for high-criticality projects',
    'contact.form.title': 'Start a conversation',
    'contact.form.subtitle': 'Tell me about your project for a more accurate response.',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Corporate Email',
    'contact.form.company': 'Company / Organization',
    'contact.form.type': 'Project type *',
    'contact.form.type.placeholder': 'Select the project type...',
    'contact.form.message': 'Message / Technical Requirement',
    'contact.form.message.placeholder': 'Tell me briefly about the context (sector, urgency, scope)...',
    'contact.form.send': 'Send Contact Protocol',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Message Sent!',
    'contact.form.success_msg': 'I respond in less than 24 business hours.',
    'contact.form.footer': 'Response in < 24h · No spam · Confidential data',
    'contact.download_cv': 'Download CV',
    'contact.type.audit': 'OT/IT Security Audit',
    'contact.type.siem': 'SIEM Implementation (Security Onion)',
    'contact.type.arch': 'IT/OT Architecture Design (Purdue Model)',
    'contact.type.network': 'Network Infrastructure – Oil & Gas',
    'contact.type.cloud': 'Virtualization and Cloud (Azure/VMware)',
    'contact.type.automation': 'Python / Power BI Automation',
    'contact.type.compliance': 'IEC 62443 / NIST / ISO 27001 Consultancy',
    'contact.type.dev': 'Web Development (Next.js / Full Stack)',
    'contact.type.other': 'Other',

    // Footer
    'footer.built_with': 'Built with Next.js 14 · Framer Motion · Three.js',
  }
}

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('es')
  const [isLoaded, setIsLoaded] = useState(false)

  // Load language on mount
  React.useEffect(() => {
    const saved = localStorage.getItem('portfolio_lang')
    if (saved === 'en' || saved === 'es') {
      setLanguage(saved as Language)
    }
    setIsLoaded(true)
  }, [])

  // Save language on change
  React.useEffect(() => {
    if (isLoaded) {
      localStorage.setItem('portfolio_lang', language)
    }
  }, [language, isLoaded])

  const t = (key: string) => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
