/**
 * Document outlines (chapter index) and search snippets for the IT/OT library.
 * Auto-generated by `npm run extract:recursos` from the real content of the
 * files in public/recursos — do not edit by hand; regenerate instead.
 */
import outlineJson from './recursos-outline.json'

export interface OutlineHeading {
  /** Heading level (1 = chapter, 2 = section, …). */
  t: number
  /** Heading text, trimmed to 120 chars. */
  x: string
}

export const RECURSO_OUTLINE: Record<string, OutlineHeading[]> = outlineJson.outline
export const RECURSO_SEARCH: Record<string, string> = outlineJson.search
